baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "hello-friend-ng"

[module]
  [[module.mounts]]
    source = 'C:/Users/Anton/Documents/Obsidian Vault/CTFBlog'
    target = 'content'
    